package com.sg.linuxgo

import android.content.Context
import androidx.preference.PreferenceManager
import java.io.File

/**
 * Experimental Wayland compatibility inspired by [tawc](https://github.com/wmww/tawc):
 * GTK3 menubar pointer-prime, XWayland env hardening, and graphics-backend prefs.
 *
 * libhybris (wmww fork, tawc v1 tree) is staged by [LibhybrisInstaller] when the
 * Wayland graphics backend is hybris (the default). It ignores the container GPU
 * driver picker and uses the phone's stock Android GLES/Vulkan blobs from glibc.
 *
 * All of this applies only when [FeatureGates.isWaylandEnabled] and container GUI is Wayland.
 * Classic X11 is unchanged except android-partition binds when hybris is on.
 */
object TawcWaylandCompat {
    const val PREF_GTK3_MENUS_WORKAROUND = "wayland_gtk3_menus_workaround"
    const val PREF_GRAPHICS_BACKEND = "wayland_tawc_graphics_backend"

    /** mesa | cpu | hybris (stock Android GPU via wmww/libhybris) */
    const val GFX_MESA = "mesa"
    const val GFX_CPU = "cpu"
    const val GFX_HYBRIS = "hybris"

    fun isGtk3MenusWorkaroundEnabled(context: Context): Boolean {
        return PreferenceManager.getDefaultSharedPreferences(context)
            .getBoolean(PREF_GTK3_MENUS_WORKAROUND, true)
    }

    fun setGtk3MenusWorkaroundEnabled(context: Context, enabled: Boolean) {
        PreferenceManager.getDefaultSharedPreferences(context).edit()
            .putBoolean(PREF_GTK3_MENUS_WORKAROUND, enabled)
            .apply()
    }

    fun graphicsBackend(context: Context): String {
        val raw = PreferenceManager.getDefaultSharedPreferences(context)
            .getString(PREF_GRAPHICS_BACKEND, null)
        return when (raw) {
            GFX_CPU, GFX_HYBRIS, GFX_MESA -> raw
            else -> if (FeatureGates.isWaylandEnabled(context)) GFX_HYBRIS else GFX_MESA
        }
    }

    fun setGraphicsBackend(context: Context, backend: String) {
        val v = when (backend) {
            GFX_CPU, GFX_HYBRIS -> backend
            else -> GFX_MESA
        }
        PreferenceManager.getDefaultSharedPreferences(context).edit()
            .putString(PREF_GRAPHICS_BACKEND, v)
            .putBoolean(LibhybrisRuntime.PREF_ENABLED, v == GFX_HYBRIS)
            .apply()
    }

    /**
     * Env extras for [WaylandActivity] / compositor process.
     * X11 path never reads these.
     */
    fun compositorEnvExtras(context: Context): Map<String, String> {
        if (!FeatureGates.isWaylandEnabled(context)) return emptyMap()
        val extras = linkedMapOf(
            "POCKETLINUX_GTK3_MENUS_WORKAROUND" to
                if (isGtk3MenusWorkaroundEnabled(context)) "1" else "0",
            "POCKETLINUX_WAYLAND_GFX" to graphicsBackend(context),
            "POCKETLINUX_TAWC_COMPAT" to "1"
        )
        extras.putAll(LibhybrisRuntime.compositorEnvExtras(context))
        return extras
    }

    /**
     * Write guest-side profile under rootfs for Wayland sessions only.
     * Sourced / exported by pocketlinux-wayland-session.
     */
    fun installGuestProfile(rootfs: File, context: Context) {
        if (!FeatureGates.isWaylandEnabled(context)) return
        val dir = File(rootfs, "etc/profile.d").apply { mkdirs() }
        val gfx = graphicsBackend(context)
        val gtk3 = if (isGtk3MenusWorkaroundEnabled(context)) "1" else "0"
        File(dir, "pocketlinux-tawc-wayland.sh").writeText(
            """
            # PocketLinux experimental Wayland / tawc-compat (do not use on X11 Lorie path)
            # Generated by TawcWaylandCompat — only meaningful when GUI_MODE=wayland.
            export POCKETLINUX_TAWC_COMPAT=1
            export POCKETLINUX_GTK3_MENUS_WORKAROUND=$gtk3
            export POCKETLINUX_WAYLAND_GFX=$gfx

            # Prefer Wayland for toolkits; X11 clients fall through to XWayland.
            export GDK_BACKEND="${'$'}{GDK_BACKEND:-wayland,x11}"
            export QT_QPA_PLATFORM="${'$'}{QT_QPA_PLATFORM:-wayland;xcb}"
            export SDL_VIDEODRIVER="${'$'}{SDL_VIDEODRIVER:-wayland,x11}"
            export CLUTTER_BACKEND="${'$'}{CLUTTER_BACKEND:-wayland}"
            export MOZ_ENABLE_WAYLAND="${'$'}{MOZ_ENABLE_WAYLAND:-1}"

            # XWayland socket discovery (labwc starts Xwayland; DISPLAY set by session script)
            export XDG_SESSION_TYPE=wayland

            case "${'$'}POCKETLINUX_WAYLAND_GFX" in
              cpu)
                export LIBGL_ALWAYS_SOFTWARE=1
                export GALLIUM_DRIVER=llvmpipe
                export MESA_LOADER_DRIVER_OVERRIDE=swrast
                unset HYBRIS_EGLPLATFORM 2>/dev/null || true
                ;;
              hybris)
                if [ -e /usr/lib/hybris/libhybris-common.so ] || [ -d /usr/lib/hybris ]; then
                  export LD_LIBRARY_PATH="/usr/lib/hybris/gl-shims:/usr/lib/hybris:${'$'}{LD_LIBRARY_PATH:-}"
                  export HYBRIS_EGLPLATFORM="${'$'}{HYBRIS_EGLPLATFORM:-wayland}"
                  export EGL_PLATFORM=wayland
                  export ANDROID_ROOT="${'$'}{ANDROID_ROOT:-/system}"
                  unset GDK_GL
                  unset LIBGL_ALWAYS_SOFTWARE GALLIUM_DRIVER MESA_LOADER_DRIVER_OVERRIDE
                  unset LIBGL_DRIVERS_PATH ZINK_DESCRIPTORS ZINK_DEBUG TU_DEBUG VK_ICD_FILENAMES
                else
                  echo "tawc-compat: hybris libs missing — falling back to Mesa" >&2
                  export POCKETLINUX_WAYLAND_GFX=mesa
                fi
                ;;
              mesa|*)
                # Stock PocketLinux Mesa/Freedreno/Zink prefs already applied by host GPU mode.
                unset HYBRIS_EGLPLATFORM 2>/dev/null || true
                ;;
            esac
            """.trimIndent() + "\n"
        )
        File(dir, "pocketlinux-tawc-wayland.sh").setReadable(true, false)
    }

    fun graphicsBackendLabel(backend: String): String = when (backend) {
        GFX_CPU -> "CPU (llvmpipe)"
        GFX_HYBRIS -> "libhybris (stock Android GPU)"
        else -> "Mesa / host GPU"
    }
}
